### ISSUE TITLE
Credit Counter Only.

### ISSUE THREAD

**Issue by rodrigosiviero** [Phillrb/MVSPlus#1]
Hi,

Would this project be possible with MVS-1B cards? I'm buying next week a South American Neogeo Cabinet, but here in Brazil we have only MVS-1B cards, which is one slot.

**Comment by Phillrb** [comment]
Hi, looking at [the manual](http://www.hardmvs.com/manuals/MV-1BusersManual.pdf) it seems that there is an 8-pin connector which would probably be fine for the current game readout. My code hooks up to the 13-pin port for the credits though and that's missing.
